allow-branch = ["main"]
sign-commit = false
sign-tag = false
tag-name = "{{crate_name}}-v{{version}}"
pre-release-commit-message = "chore: release {{crate_name}} v{{version}}"
tag-message = "{{crate_name}} v{{version}}"
