[package]
name = "ensemble-bridge-midi"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
ensemble-core = { path = "../ensemble-core" }
ensemble-client = { path = "../ensemble-client" }
tokio = { version = "1", features = ["full"] }
midir = "0.10"
anyhow = "1"
