[package]
name = "ensemble-client"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Client library for connecting to an Ensemble hub"
repository.workspace = true
homepage.workspace = true
readme = "README.md"

[dependencies]
ensemble-core = { version = "0.1.0", path = "../ensemble-core" }
ensemble-discovery = { version = "0.1.0", path = "../ensemble-discovery" }
ensemble-clock = { version = "0.1.0", path = "../ensemble-clock" }
tokio = { version = "1", features = ["net", "rt", "sync", "time", "macros"] }
tracing = "0.1"

[dev-dependencies]
tokio = { version = "1", features = ["full"] }
ensemble-routing = { version = "0.1.0", path = "../ensemble-routing" }
