[package]
name = "ensemble-client"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
ensemble-core = { path = "../ensemble-core" }
ensemble-discovery = { path = "../ensemble-discovery" }
ensemble-clock = { path = "../ensemble-clock" }
tokio = { version = "1", features = ["net", "rt", "sync", "time", "macros"] }
tracing = "0.1"

[dev-dependencies]
tokio = { version = "1", features = ["full"] }
ensemble-routing = { path = "../ensemble-routing" }
